# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1003, 705)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setStyleSheet("QFrame{\n"
"    background-color: rgb(243, 243, 243);\n"
"}")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_manu = QtWidgets.QFrame(self.frame_content)
        self.frame_manu.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_manu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_manu.setStyleSheet("QFrame{\n"
"    background-color: rgb(207, 207, 207);\n"
"}")
        self.frame_manu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_manu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_manu.setObjectName("frame_manu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_manu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_menu1 = QtWidgets.QPushButton(self.frame_manu)
        self.pushButton_menu1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 174, 236);\n"
"    border:none;\n"
"    height:35px;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(65, 184, 131);\n"
"}")
        self.pushButton_menu1.setObjectName("pushButton_menu1")
        self.verticalLayout.addWidget(self.pushButton_menu1)
        self.pushButton_menu2 = QtWidgets.QPushButton(self.frame_manu)
        self.pushButton_menu2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 174, 236);\n"
"    border:none;\n"
"    height:35px;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(65, 184, 131);\n"
"}")
        self.pushButton_menu2.setObjectName("pushButton_menu2")
        self.verticalLayout.addWidget(self.pushButton_menu2)
        self.pushButton_menu3 = QtWidgets.QPushButton(self.frame_manu)
        self.pushButton_menu3.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 174, 236);\n"
"    border:none;\n"
"    height:35px;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(65, 184, 131);\n"
"}")
        self.pushButton_menu3.setObjectName("pushButton_menu3")
        self.verticalLayout.addWidget(self.pushButton_menu3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame_manu)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_content)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addWidget(self.frame_content)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setStyleSheet("QStatusBar{\n"
"    background-color: rgb(183, 255, 49);\n"
"}")
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.pushButton_menu1.clicked.connect(self.lineEdit.paste)
        self.pushButton_menu2.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "主页面"))
        self.pushButton_menu1.setText(_translate("mainWindow", "菜单1"))
        self.pushButton_menu2.setText(_translate("mainWindow", "菜单2"))
        self.pushButton_menu3.setText(_translate("mainWindow", "菜单3"))
